/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sources: Source;
    'prompt-artifacts': PromptArtifact;
    'taxonomy-nodes': TaxonomyNode;
    'page-records': PageRecord;
    'locale-variants': LocaleVariant;
    edges: Edge;
    'audit-events': AuditEvent;
    'module-envelopes': ModuleEnvelope;
    'media-evidence': MediaEvidence;
    'page-projections': PageProjection;
    'publication-snapshots': PublicationSnapshot;
    'publication-states': PublicationState;
    'active-publication-pointers': ActivePublicationPointer;
    redirects: Redirect;
    'workflow-runs': WorkflowRun;
    'deletion-requests': DeletionRequest;
    'golden-replacement-approvals': GoldenReplacementApproval;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'prompt-artifacts': PromptArtifactsSelect<false> | PromptArtifactsSelect<true>;
    'taxonomy-nodes': TaxonomyNodesSelect<false> | TaxonomyNodesSelect<true>;
    'page-records': PageRecordsSelect<false> | PageRecordsSelect<true>;
    'locale-variants': LocaleVariantsSelect<false> | LocaleVariantsSelect<true>;
    edges: EdgesSelect<false> | EdgesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'module-envelopes': ModuleEnvelopesSelect<false> | ModuleEnvelopesSelect<true>;
    'media-evidence': MediaEvidenceSelect<false> | MediaEvidenceSelect<true>;
    'page-projections': PageProjectionsSelect<false> | PageProjectionsSelect<true>;
    'publication-snapshots': PublicationSnapshotsSelect<false> | PublicationSnapshotsSelect<true>;
    'publication-states': PublicationStatesSelect<false> | PublicationStatesSelect<true>;
    'active-publication-pointers': ActivePublicationPointersSelect<false> | ActivePublicationPointersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'workflow-runs': WorkflowRunsSelect<false> | WorkflowRunsSelect<true>;
    'deletion-requests': DeletionRequestsSelect<false> | DeletionRequestsSelect<true>;
    'golden-replacement-approvals': GoldenReplacementApprovalsSelect<false> | GoldenReplacementApprovalsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | (
        | 'en'
        | 'zh-CN'
        | 'zh-TW'
        | 'ja-JP'
        | 'ko-KR'
        | 'de-DE'
        | 'fr-FR'
        | 'it-IT'
        | 'es-ES'
        | 'es-419'
        | 'pt-BR'
        | 'pt-PT'
        | 'hi-IN'
        | 'th-TH'
        | 'tr-TR'
        | 'vi-VN'
      )
    | (
        | 'en'
        | 'zh-CN'
        | 'zh-TW'
        | 'ja-JP'
        | 'ko-KR'
        | 'de-DE'
        | 'fr-FR'
        | 'it-IT'
        | 'es-ES'
        | 'es-419'
        | 'pt-BR'
        | 'pt-PT'
        | 'hi-IN'
        | 'th-TH'
        | 'tr-TR'
        | 'vi-VN'
      )[];
  globals: {};
  globalsSelect: {};
  locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  stable_id: string;
  identity_kind: 'human' | 'service';
  roles?: ('admin' | 'editor' | 'translator' | 'reviewer' | 'publisher' | 'legal')[] | null;
  /**
   * Only dedicated service identities may receive a service scope.
   */
  service_scopes?: ('ingest' | 'translate' | 'publish' | 'withdraw')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  object_ref:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'superseded' | 'removed';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  provider: 'twitter241' | 'first_party' | 'submission' | 'official_doc';
  provider_record_id: string;
  canonical_url: string;
  raw_ref:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  captured_at: string;
  content_hash: string;
  author_ref?: (number | null) | TaxonomyNode;
  rights_state:
    | 'unknown'
    | 'metadata_only'
    | 'display_licensed'
    | 'redistribution_licensed'
    | 'first_party'
    | 'blocked'
    | 'revoked';
  rights_basis?: string | null;
  deletion_state: 'active' | 'requested' | 'removed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy-nodes".
 */
export interface TaxonomyNode {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'retired';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  node_type: 'output' | 'model' | 'use_case' | 'style' | 'technique' | 'creator' | 'subject';
  stable_key: string;
  label: string;
  description?: string | null;
  promotion_state: 'candidate' | 'reviewed' | 'qualified' | 'retired';
  evidence_refs?: (number | Source)[] | null;
  inventory_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-artifacts".
 */
export interface PromptArtifact {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'draft' | 'review' | 'approved' | 'published' | 'blocked' | 'withdrawn';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  kind: 'prompt' | 'workflow' | 'comparison';
  canonical_label: string;
  prompt: {
    original_text: string;
    variables?:
      | {
          token: string;
          description?: string | null;
          allowed_values?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          occurrences?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  original_language: string;
  outcome?: {
    media_type?: ('image' | 'video' | 'unresolved') | null;
    summary?: string | null;
    capability?: string | null;
  };
  inputs?: {
    required?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    optional?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  parameters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  examples?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflow_steps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  signals?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source: number | Source;
  model_refs?: (number | TaxonomyNode)[] | null;
  taxonomy_refs?: (number | TaxonomyNode)[] | null;
  variation_refs?: (number | PromptArtifact)[] | null;
  rights_state:
    | 'unknown'
    | 'metadata_only'
    | 'display_licensed'
    | 'redistribution_licensed'
    | 'first_party'
    | 'blocked'
    | 'revoked';
  safety_state: 'pending' | 'approved' | 'blocked';
  evidence_state: 'pending' | 'verified' | 'insufficient';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-records".
 */
export interface PageRecord {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'retired';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  page_type: 'hub' | 'gallery' | 'entity' | 'detail';
  locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  root_object:
    | {
        relationTo: 'prompt-artifacts';
        value: number | PromptArtifact;
      }
    | {
        relationTo: 'taxonomy-nodes';
        value: number | TaxonomyNode;
      };
  /**
   * Canonical typed root object identity for SQL uniqueness.
   */
  root_object_key: string;
  intent: string;
  primary_keyword_by_locale?:
    | {
        locale:
          | 'en'
          | 'zh-CN'
          | 'zh-TW'
          | 'ja-JP'
          | 'ko-KR'
          | 'de-DE'
          | 'fr-FR'
          | 'it-IT'
          | 'es-ES'
          | 'es-419'
          | 'pt-BR'
          | 'pt-PT'
          | 'hi-IN'
          | 'th-TH'
          | 'tr-TR'
          | 'vi-VN';
        keyword: string;
        id?: string | null;
      }[]
    | null;
  inventory:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  demand_evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  information_gain?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qualification_score:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  qualification_input_hash: string;
  qualification_rule_version: string;
  approval_edge?: (number | null) | Edge;
  approval_evidence?: (number | Source)[] | null;
  index_state: 'not_generated' | 'discoverable_noindex' | 'index_candidate' | 'indexable' | 'retired';
  reason_codes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edges".
 */
export interface Edge {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'retired';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  from:
    | {
        relationTo: 'sources';
        value: number | Source;
      }
    | {
        relationTo: 'prompt-artifacts';
        value: number | PromptArtifact;
      }
    | {
        relationTo: 'taxonomy-nodes';
        value: number | TaxonomyNode;
      };
  from_key: string;
  relation:
    | 'generated_with'
    | 'used_for'
    | 'produces'
    | 'has_style'
    | 'uses_technique'
    | 'depicts'
    | 'targets_audience'
    | 'created_by'
    | 'sourced_from'
    | 'variation_of'
    | 'member_of'
    | 'compared_with'
    | 'requires_input';
  legacy_relation_label?: string | null;
  relation_migration_state?: ('canonical' | 'requires_review') | null;
  to:
    | {
        relationTo: 'sources';
        value: number | Source;
      }
    | {
        relationTo: 'prompt-artifacts';
        value: number | PromptArtifact;
      }
    | {
        relationTo: 'taxonomy-nodes';
        value: number | TaxonomyNode;
      };
  to_key: string;
  evidence: (number | Source)[];
  confidence: number;
  review_state: 'candidate' | 'approved' | 'rejected';
  valid_from?: string | null;
  valid_to?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locale-variants".
 */
export interface LocaleVariant {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'withdrawn';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  entity:
    | {
        relationTo: 'prompt-artifacts';
        value: number | PromptArtifact;
      }
    | {
        relationTo: 'taxonomy-nodes';
        value: number | TaxonomyNode;
      }
    | {
        relationTo: 'page-records';
        value: number | PageRecord;
      };
  entity_key: string;
  locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  source_locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  translation_model: string;
  translation_prompt_version: string;
  localized_fields:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  content_revision: number;
  quality?: {
    terminology_score?: number | null;
    placeholder_integrity?: ('pass' | 'fail') | null;
    factual_consistency?: ('pass' | 'fail') | null;
    language_detection?: ('pass' | 'fail') | null;
    human_score?: number | null;
  };
  workflow_state: 'missing' | 'machine_draft' | 'review' | 'approved' | 'published' | 'blocked' | 'stale' | 'withdrawn';
  reviewed_by?: (number | null) | User;
  reviewed_by_stable_id?: string | null;
  reviewed_revision?: number | null;
  last_content_editor?: (number | null) | User;
  last_content_editor_stable_id?: string | null;
  is_money_page: boolean;
  risk_classes?: ('money' | 'comparison' | 'price' | 'legal_rights')[] | null;
  reviewed_at?: string | null;
  published_version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'recorded';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  event_id: string;
  actor_user?: (number | null) | User;
  actor_type: 'user' | 'service' | 'anonymous';
  actor_stable_id: string;
  actor_service?: string | null;
  correlation_id: string;
  causation_id?: string | null;
  event_type: string;
  entity_type: string;
  entity_stable_id: string;
  outcome: 'allowed' | 'denied' | 'failed';
  prior_state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  new_state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason_code?: string | null;
  occurred_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-envelopes".
 */
export interface ModuleEnvelope {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'active' | 'blocked' | 'stale';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  module_id: string;
  page_id: string;
  locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  module_type: 'case' | 'tutorial' | 'prompt' | 'comparison' | 'faq' | 'examples' | 'provenance' | 'action';
  module_version: number;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slot_key?: string | null;
  position?: number | null;
  dependency_refs?:
    | (
        | {
            relationTo: 'sources';
            value: number | Source;
          }
        | {
            relationTo: 'module-envelopes';
            value: number | ModuleEnvelope;
          }
      )[]
    | null;
  dependency_hash?: string | null;
  quality_result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  risk_classes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  visibility?: ('private' | 'internal_preview' | 'public') | null;
  renderer_version?: string | null;
  stale_reason?: string | null;
  source_refs: (number | Source)[];
  rights_state:
    | 'unknown'
    | 'metadata_only'
    | 'display_licensed'
    | 'redistribution_licensed'
    | 'first_party'
    | 'blocked'
    | 'revoked';
  content_hash: string;
  generated_by: 'human' | 'rule' | 'rpa' | 'llm';
  generator_version?: string | null;
  observed_at: string;
  expires_at?: string | null;
  review_state: 'candidate' | 'approved' | 'blocked' | 'stale';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-evidence".
 */
export interface MediaEvidence {
  id: number;
  media_evidence_id: string;
  source_ref: number | Source;
  source_version: string;
  workflow_run: number | WorkflowRun;
  provider: 'x' | 'approved_cdn' | 'first_party';
  provider_media_id: string;
  media_type: 'image' | 'video';
  width?: number | null;
  height?: number | null;
  duration_ms?: number | null;
  remote_url: string;
  thumbnail_url?: string | null;
  observed_at: string;
  rights_state:
    | 'unknown'
    | 'metadata_only'
    | 'display_licensed'
    | 'redistribution_licensed'
    | 'first_party'
    | 'blocked'
    | 'revoked';
  sensitive_content_state: 'unknown' | 'allowed' | 'restricted' | 'blocked';
  content_hash: string;
  visibility: 'private_evidence' | 'internal_preview' | 'public';
  delivery_target: 'private_reference' | 'x_cdn' | 'approved_public_cdn';
  preview_noindex: boolean;
  attribution_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs".
 */
export interface WorkflowRun {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'stale_ignored';
  audit: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  job_type:
    | 'ingest'
    | 'translate'
    | 'browser'
    | 'publish'
    | 'export'
    | 'withdraw'
    | 'extract_graph'
    | 'generate_module'
    | 'project_page'
    | 'validate_release'
    | 'observe_search';
  idempotency_key: string;
  attempt: number;
  input_ref: string;
  output_ref?: string | null;
  error_class?: string | null;
  lease_owner?: string | null;
  lease_expires_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-projections".
 */
export interface PageProjection {
  id: number;
  projection_id: string;
  page_id: string;
  locale:
    | 'en'
    | 'de'
    | 'es'
    | 'fr'
    | 'it'
    | 'ja'
    | 'ko'
    | 'nl'
    | 'pl'
    | 'pt-BR'
    | 'ru'
    | 'sv'
    | 'tr'
    | 'zh-CN'
    | 'zh-TW'
    | 'ar';
  family: 'hub' | 'gallery' | 'entity' | 'detail';
  state: 'draft' | 'validated' | 'released' | 'superseded' | 'withdrawn';
  /**
   * Renderer-only page, navigation, and slot contract.
   */
  projection:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dependency_hash: string;
  content_hash: string;
  link_hash: string;
  schema_hash: string;
  renderer_version: string;
  validation_report_ref: string;
  workflow_run: number | WorkflowRun;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-snapshots".
 */
export interface PublicationSnapshot {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'recorded';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  publish_version: number;
  route_manifest_ref: string;
  sitemap_manifest_ref: string;
  github_manifest_ref: string;
  content_tree_hash: string;
  previous_verified_version?: number | null;
  validation_report_ref: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-states".
 */
export interface PublicationState {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'draft' | 'preparing' | 'validated' | 'active' | 'superseded' | 'rolled_back' | 'failed';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  publish_version: number;
  reason_code?: string | null;
  activated_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-publication-pointers".
 */
export interface ActivePublicationPointer {
  id: number;
  stable_id: string;
  revision: number;
  singleton_key: string;
  publish_version?: number | null;
  previous_verified_version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: '301' | '308' | '410';
  audit: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  locale:
    | 'en'
    | 'zh-CN'
    | 'zh-TW'
    | 'ja-JP'
    | 'ko-KR'
    | 'de-DE'
    | 'fr-FR'
    | 'it-IT'
    | 'es-ES'
    | 'es-419'
    | 'pt-BR'
    | 'pt-PT'
    | 'hi-IN'
    | 'th-TH'
    | 'tr-TR'
    | 'vi-VN';
  old_path: string;
  target_path?: string | null;
  reason_code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-requests".
 */
export interface DeletionRequest {
  id: number;
  stable_id: string;
  revision: number;
  schema_version: number;
  source_version: string;
  status: 'received' | 'validated' | 'withdrawing' | 'surfaces_pending' | 'completed' | 'rejected' | 'cancelled';
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  external_request_key: string;
  scope: 'source' | 'artifact' | 'locale' | 'page' | 'export';
  requested_by: number | User;
  legal_basis: string;
  object_refs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deadline?: string | null;
  reason_code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "golden-replacement-approvals".
 */
export interface GoldenReplacementApproval {
  id: number;
  stable_id?: string | null;
  revision?: number | null;
  schema_version?: number | null;
  source_version?: string | null;
  status?: 'recorded' | null;
  audit?: {
    created_by?: (number | null) | User;
    updated_by?: (number | null) | User;
    correlation_id?: string | null;
  };
  baseline_manifest_hash: string;
  candidate_manifest_hash: string;
  evaluator_version: string;
  reviewer_user?: (number | null) | User;
  reviewer_actor_id?: string | null;
  reviewer_role?: 'reviewer' | null;
  correlation_id: string;
  approved_at?: string | null;
  audit_ref?: string | null;
  audit_outcome?: 'allowed' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'prompt-artifacts';
        value: number | PromptArtifact;
      } | null)
    | ({
        relationTo: 'taxonomy-nodes';
        value: number | TaxonomyNode;
      } | null)
    | ({
        relationTo: 'page-records';
        value: number | PageRecord;
      } | null)
    | ({
        relationTo: 'locale-variants';
        value: number | LocaleVariant;
      } | null)
    | ({
        relationTo: 'edges';
        value: number | Edge;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'module-envelopes';
        value: number | ModuleEnvelope;
      } | null)
    | ({
        relationTo: 'media-evidence';
        value: number | MediaEvidence;
      } | null)
    | ({
        relationTo: 'page-projections';
        value: number | PageProjection;
      } | null)
    | ({
        relationTo: 'publication-snapshots';
        value: number | PublicationSnapshot;
      } | null)
    | ({
        relationTo: 'publication-states';
        value: number | PublicationState;
      } | null)
    | ({
        relationTo: 'active-publication-pointers';
        value: number | ActivePublicationPointer;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'workflow-runs';
        value: number | WorkflowRun;
      } | null)
    | ({
        relationTo: 'deletion-requests';
        value: number | DeletionRequest;
      } | null)
    | ({
        relationTo: 'golden-replacement-approvals';
        value: number | GoldenReplacementApproval;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  stable_id?: T;
  identity_kind?: T;
  roles?: T;
  service_scopes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  object_ref?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  provider?: T;
  provider_record_id?: T;
  canonical_url?: T;
  raw_ref?: T;
  captured_at?: T;
  content_hash?: T;
  author_ref?: T;
  rights_state?: T;
  rights_basis?: T;
  deletion_state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-artifacts_select".
 */
export interface PromptArtifactsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  kind?: T;
  canonical_label?: T;
  prompt?:
    | T
    | {
        original_text?: T;
        variables?:
          | T
          | {
              token?: T;
              description?: T;
              allowed_values?: T;
              occurrences?: T;
              id?: T;
            };
      };
  original_language?: T;
  outcome?:
    | T
    | {
        media_type?: T;
        summary?: T;
        capability?: T;
      };
  inputs?:
    | T
    | {
        required?: T;
        optional?: T;
      };
  parameters?: T;
  examples?: T;
  workflow_steps?: T;
  signals?: T;
  source?: T;
  model_refs?: T;
  taxonomy_refs?: T;
  variation_refs?: T;
  rights_state?: T;
  safety_state?: T;
  evidence_state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy-nodes_select".
 */
export interface TaxonomyNodesSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  node_type?: T;
  stable_key?: T;
  label?: T;
  description?: T;
  promotion_state?: T;
  evidence_refs?: T;
  inventory_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-records_select".
 */
export interface PageRecordsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  page_type?: T;
  locale?: T;
  root_object?: T;
  root_object_key?: T;
  intent?: T;
  primary_keyword_by_locale?:
    | T
    | {
        locale?: T;
        keyword?: T;
        id?: T;
      };
  inventory?: T;
  demand_evidence?: T;
  information_gain?: T;
  qualification_score?: T;
  qualification_input_hash?: T;
  qualification_rule_version?: T;
  approval_edge?: T;
  approval_evidence?: T;
  index_state?: T;
  reason_codes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locale-variants_select".
 */
export interface LocaleVariantsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  entity?: T;
  entity_key?: T;
  locale?: T;
  source_locale?: T;
  translation_model?: T;
  translation_prompt_version?: T;
  localized_fields?: T;
  content_revision?: T;
  quality?:
    | T
    | {
        terminology_score?: T;
        placeholder_integrity?: T;
        factual_consistency?: T;
        language_detection?: T;
        human_score?: T;
      };
  workflow_state?: T;
  reviewed_by?: T;
  reviewed_by_stable_id?: T;
  reviewed_revision?: T;
  last_content_editor?: T;
  last_content_editor_stable_id?: T;
  is_money_page?: T;
  risk_classes?: T;
  reviewed_at?: T;
  published_version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edges_select".
 */
export interface EdgesSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  from?: T;
  from_key?: T;
  relation?: T;
  legacy_relation_label?: T;
  relation_migration_state?: T;
  to?: T;
  to_key?: T;
  evidence?: T;
  confidence?: T;
  review_state?: T;
  valid_from?: T;
  valid_to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  event_id?: T;
  actor_user?: T;
  actor_type?: T;
  actor_stable_id?: T;
  actor_service?: T;
  correlation_id?: T;
  causation_id?: T;
  event_type?: T;
  entity_type?: T;
  entity_stable_id?: T;
  outcome?: T;
  prior_state?: T;
  new_state?: T;
  reason_code?: T;
  occurred_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-envelopes_select".
 */
export interface ModuleEnvelopesSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  module_id?: T;
  page_id?: T;
  locale?: T;
  module_type?: T;
  module_version?: T;
  payload?: T;
  slot_key?: T;
  position?: T;
  dependency_refs?: T;
  dependency_hash?: T;
  quality_result?: T;
  risk_classes?: T;
  visibility?: T;
  renderer_version?: T;
  stale_reason?: T;
  source_refs?: T;
  rights_state?: T;
  content_hash?: T;
  generated_by?: T;
  generator_version?: T;
  observed_at?: T;
  expires_at?: T;
  review_state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-evidence_select".
 */
export interface MediaEvidenceSelect<T extends boolean = true> {
  media_evidence_id?: T;
  source_ref?: T;
  source_version?: T;
  workflow_run?: T;
  provider?: T;
  provider_media_id?: T;
  media_type?: T;
  width?: T;
  height?: T;
  duration_ms?: T;
  remote_url?: T;
  thumbnail_url?: T;
  observed_at?: T;
  rights_state?: T;
  sensitive_content_state?: T;
  content_hash?: T;
  visibility?: T;
  delivery_target?: T;
  preview_noindex?: T;
  attribution_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-projections_select".
 */
export interface PageProjectionsSelect<T extends boolean = true> {
  projection_id?: T;
  page_id?: T;
  locale?: T;
  family?: T;
  state?: T;
  projection?: T;
  dependency_hash?: T;
  content_hash?: T;
  link_hash?: T;
  schema_hash?: T;
  renderer_version?: T;
  validation_report_ref?: T;
  workflow_run?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-snapshots_select".
 */
export interface PublicationSnapshotsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  publish_version?: T;
  route_manifest_ref?: T;
  sitemap_manifest_ref?: T;
  github_manifest_ref?: T;
  content_tree_hash?: T;
  previous_verified_version?: T;
  validation_report_ref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-states_select".
 */
export interface PublicationStatesSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  publish_version?: T;
  reason_code?: T;
  activated_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-publication-pointers_select".
 */
export interface ActivePublicationPointersSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  singleton_key?: T;
  publish_version?: T;
  previous_verified_version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  locale?: T;
  old_path?: T;
  target_path?: T;
  reason_code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs_select".
 */
export interface WorkflowRunsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  job_type?: T;
  idempotency_key?: T;
  attempt?: T;
  input_ref?: T;
  output_ref?: T;
  error_class?: T;
  lease_owner?: T;
  lease_expires_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-requests_select".
 */
export interface DeletionRequestsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  external_request_key?: T;
  scope?: T;
  requested_by?: T;
  legal_basis?: T;
  object_refs?: T;
  deadline?: T;
  reason_code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "golden-replacement-approvals_select".
 */
export interface GoldenReplacementApprovalsSelect<T extends boolean = true> {
  stable_id?: T;
  revision?: T;
  schema_version?: T;
  source_version?: T;
  status?: T;
  audit?:
    | T
    | {
        created_by?: T;
        updated_by?: T;
        correlation_id?: T;
      };
  baseline_manifest_hash?: T;
  candidate_manifest_hash?: T;
  evaluator_version?: T;
  reviewer_user?: T;
  reviewer_actor_id?: T;
  reviewer_role?: T;
  correlation_id?: T;
  approved_at?: T;
  audit_ref?: T;
  audit_outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}